apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-consumer
  template:
    metadata:
      labels:
        app: spark-consumer
    spec:
      restartPolicy: Always
      containers:
        - name: spark-consumer
          image: ducchankawaii/stream-hdfs:latest
          imagePullPolicy: Always
          env:
            - name: SPARK_MASTER_URL
              value: spark://spark-master.default.svc.cluster.local:7077
            # - name: HDFS_URL
            #   value: hdfs://hdfs-namenode.default.svc.cluster.local:8020
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-broker1:9092,kafka-broker2:9092
            - name: SPARK_EXECUTOR_MEMORY
              value: "2g"
            - name: SPARK_EXECUTOR_MEMORY_OVERHEAD
              value: "512m"
            - name: SPARK_EXECUTOR_CORES 
              value: "1"
          resources:
            requests:
              memory: "2.5Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          volumeMounts:
            - name: spark-checkpoint
              mountPath: /app/checkpoint
      volumes:
        - name: spark-checkpoint
          emptyDir: {}