apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-consumer
  namespace: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-consumer
  template:
    metadata:
      labels:
        app: spark-consumer
    spec:
      containers:
      - name: spark-consumer
        image: ducchankawaii/pyspark-kafka:latest
        ports:
        - containerPort: 7077