# Spark Master Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      role: master
  template:
    metadata:
      labels:
        app: spark
        role: master
    spec:
      containers:
        - name: spark-master
          image: apache/spark:3.5.1
          command:
            - /opt/spark/bin/spark-class
          args:
            - org.apache.spark.deploy.master.Master
          env:
            - name: SPARK_MODE
              value: master
            - name: SPARK_MASTER_PORT
              value: "7077"
            - name: SPARK_MASTER_WEBUI_PORT
              value: "8080"
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "400m"
            limits:
              memory: "512Mi"
              cpu: "800m"
---
# Spark Master Service
apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  selector:
    app: spark
    role: master
  ports:
    - name: master-rpc
      port: 7077
      targetPort: 7077
    - name: master-web
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
# Spark Worker StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-worker
spec:
  serviceName: spark-worker-headless
  replicas: 1
  selector:
    matchLabels:
      app: spark
      role: worker
  template:
    metadata:
      labels:
        app: spark
        role: worker
    spec:
      containers:
        - name: spark-worker
          image: apache/spark:3.5.1
          command:
            - /bin/sh
            - -c
          args:
            - |
              cp /opt/spark/jars/kafka-clients-* /opt/spark/jars/
              /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master.default.svc.cluster.local:7077
          env:
            - name: SPARK_MODE
              value: worker
            - name: SPARK_WORKER_WEBUI_PORT
              value: "8081"
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "3Gi"
              cpu: "1"
---
# Spark Worker Headless Service
apiVersion: v1
kind: Service
metadata:
  name: spark-worker-headless
spec:
  ports:
    - name: worker-web
      port: 8081
      targetPort: 8081
  clusterIP: None
  selector:
    app: spark
    role: worker
